name: NPM Publish
# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
      - name: Configure Git
        run: |
          git checkout $(echo $GITHUB_REF | sed 's/refs\/heads\///') \
            && git config --local user.email "$(git log -1 --pretty=format:'%ae')" \
            && git config --local user.name "$(git log -1 --pretty=format:'%an')" \
            && git config --local credential.helper store \
            && echo "https://${{secrets.GIT_TOKEN}}:x-oauth-basic@github.com" >> "$HOME/.git-credentials"
      - name: Install Dependencies
        run: yarn install && yarn lerna:bootstrap
      - name: Release
        run: yarn lerna:publish -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
